version: '3.5'
services:
  db:
    image: mysql:8
    container_name: simple_pos
    environment:
      - MYSQL_DATABASE=simple_pos
      - MYSQL_USER=simple_pos
      - MYSQL_PASSWORD=strongrootpassword
      - MYSQL_ROOT_PASSWORD=strongrootpassword
    ports:
     - "3306:3306"